kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

pipeline:
- name: build-fips-unittest
  image: amarburg/lsdslam-dev-host
  commands:
    - ./fips set config linux-make-unittest
    - ./fips build

- name: trigger-github-downstream
  image: plugins/downstream
  settings:
    server: https://github.drone.camhd.science
    fork: true
    token:
      from_secret: github_drone_token
    repositories:
      - apl-ocean-engineering/serdp_player

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
  when:
    status: [ success, failure ]
